sudo: required
services:
  - docker

setup:
  - git clone https://github.com/annie-annie/docker-react-aws.git
  - cd docker-react-aws

before_install:
  - docker build -t hello -f Dockerfile.dev .

script:
  - docker run hello yarn test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'docker-react-aws'
  env: 'DockerReacrtAws-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-663264990597'
  bucket_path: 'docker-reacrt-aws'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: main
