sudo: required
services:
  - docker

setup:
  - git clone https://github.com/annie-annie/docker-react-aws.git
  - cd docker-react-aws

before_install:
  - docker build -t hello -f Dockerfile.dev .

script:
  - docker run hello yarn test
