version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dra_web
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
